int factorial_rec(int a);
int factorial(int a);
int suma(int a, int b);
int resta(int a, int b);
int multiplicacion(int a, int b);
int fibonacci(int valor, int meta);
int fibonacci_hasta(int valor);
double division(int a, int b);
double euler(int a);
double pi (int valor);